[project]
name = "django-site-labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "dotenv>=0.9.9",
    "pillow>=12.1.0",
    "psycopg[binary]>=3.3.2",
]
